/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

import buildcfg.Libs

plugins {
    id(GradlePluginId.ANDROID_LIBRARY)
    id(GradlePluginId.KOTLIN_ANDROID)
    id(GradlePluginId.KOTLIN_KAPT)
    id(GradlePluginId.MAVEN_PUBLISH)
}

android {
    compileSdk = AndroidConfig.COMPILE_SDK_VERSION
    buildToolsVersion = AndroidConfig.BUILD_TOOLS_VERSION
    defaultConfig {
        minSdk = AndroidConfig.MIN_SDK_VERSION
        targetSdk = AndroidConfig.TARGET_SDK_VERSION
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        getByName("release") {
            consumerProguardFiles("consumer-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = buildcfg.Versions.JAVA_VERSION
        targetCompatibility = buildcfg.Versions.JAVA_VERSION
    }
}

dependencies {
    api(Libs.Kotlin.kotlinStdlib8)
    api(Libs.Coroutines.coroutinesCore)

    implementation(Libs.OkHttp.okhttp)
    implementation(Libs.Wire.wireCoroutines)

    testImplementation(Libs.AndroidX.Test.Ext.junit)
    testImplementation(Libs.AndroidX.Test.Ext.truth)
    androidTestImplementation(Libs.AndroidX.Test.Ext.junit)
    androidTestImplementation(Libs.AndroidX.Test.Ext.truth)
    androidTestImplementation(Libs.AndroidX.Test.runner)
}
